### ISSUE TITLE
Pytest errors

### ISSUE THREAD

**Issue by Biplingo** [IMC-UAS-Krems/ADSI2ILV-SS23-playground-and-homework#6] opened 2023-03-09 10:45 UTC
Has anyone encountered something similar?
I have trouble solving it, I tried renaming files as well as removing the cache.

When not starting the tests with a file specified this error occurs:
![image](https://user-images.githubusercontent.com/114472101/223992491-5bd0cabb-8488-40f6-b3f2-671e66e674ae.png)
removing the file suggested in HINT did not solve the issue

If the file is renamed this error occurs:
![image](https://user-images.githubusercontent.com/114472101/223992966-4e5d49bb-b72b-47df-a5aa-3e358a48ea5b.png)

**Comment by alessiogambi** [comment] 2023-03-12 14:48
The issue is in the imports. This is fixed by #7

**Closed as completed by alessiogambi** 2023-03-12 14:48 UTC
